# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9abd968d651f85fec742fad0ade9a92436dabcba69888580e500bd40cd60327ae7b8d83a577cb53e25e1ee1c02b4be0099843166484395729d2335fcba3ae6ca

test:
  secret_key_base: 7ef70688342bab0614725de1f79d85105ebf296700bad7538222bd50e68c92706f59b5543eddd65e43cb10d80f738f9ec1938f55bf55d93a0502b7633f59ea48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
